### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by michaelii** [Acovea/libacovea#1]
Hi I am Michael

I got the issue when I install the acovea

The issue is the same like this website
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=653744

Does Acovea tool still can use or not?
I need the help

Thanks

Michael
University of Texas at Arlington

**Comment by Randl** [comment]
The issue is probably connected to the incompatibility between old and new version of compilers. 

I suppose you to try to fix it your self if you have experience in C++. If not, I'll try to fix it, but it probably won't happen too soon (next month maybe)

**Comment by Randl** [comment]
I tried to fix the problems, and fixed the trivial part (see https://github.com/Acovea/libacovea/commit/5f4ab7f9073606d0eee6958e4432235b99b86b71 https://github.com/Acovea/libcoyotl/commit/84642d2a26abce6303dea038f58d0beccf3bb3d9 https://github.com/Acovea/libevocosm/commit/47e4427242e2f051dabe3fb1b5c670b2d915c899 https://github.com/Acovea/libevocosm/commit/7abacd468a695abe693de484cf6d70dc10a16b76 ). `libevocosm` and `libcoyotl` are building on ly local machine now (Ubuntu 16.04). `libacovea` doesn't builds yet.

**Comment by Randl** [comment]
Hi @michaelii 

I believe I managed to fix the issues. Can you confirm acovea compiles with https://github.com/Acovea/libevocosm/tree/v3.1.0 https://github.com/Acovea/libcoyotl/tree/bddaf2f9e78375336d0ae9a7f0c0d6d2313cba47 and https://github.com/Acovea/libacovea/tree/8545b8095f679dceafebab869b81410cc7a5b489 ?

**Comment by michaelii** [comment]
Hi @Randl 

I will check it this two days

Thanks

Michael
University of Texas at Arlington

**Comment by michaelii** [comment]
Hi @Randl 

I try to install all package use command.
It is good to Install
But I got some situation when I want to execute the command "runacovea"

1. "runacovea" the command is good. It shows all information about help menu.
2. When I try to run the example command 
    "runacovea –config config-file-name –input source-file-name"
    It will shows Segment fail (Core dump)

It looks like the application crash because of setting.
Even I try to put the file which does not exist, it still only show  "Segment fail (Core dump)".
It looks like the application get the issue in the beginning before load file.
I have no idea for the detail setting about Core dump issue.
This is the issue.

My OS is Ubuntu 16.0.4. Currently, my system is crash because of the other project. I will try to re-install and it. If you want to more detail information for issue fix. Please let me know. I will send it to you ASAP.

Thanks

Michael
University of Texas at Arlington

**Comment by Randl** [comment]
Hi @michaelii 

I'd ask you to compile acovea and all libs with debug flags and to get as much information as possible. And open a new issue for that.

Regards,
Evgeniy
